branch-defaults:
  ebconfig:
    environment: mementor-integration
  master:
    environment: mementor-integration
deploy:
  artifact: target/mementor-aws.zip
environment-defaults:
  mementor-integration:
    branch: null
    repository: null
global:
  application_name: mementor
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2018.03 v2.14.0 running Docker 18.09.9-ce
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
