# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-stretch-node

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "front-end/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - run: npm --prefix front-end install

      - save_cache:
          paths:
            - ~/.m2
            - front-end/node_modules
          key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "front-end/package.json" }}

      - run: mvn package -B
      - run: npm --prefix front-end test

      - run: docker build .

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/
